name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set PR in env
        run: echo "GITHUB_PR_NUMBER=$(echo $GITHUB_REF | awk -F / '{print $3}')" >> $GITHUB_ENV
      - run: echo "pageLoadTimeout=150000,baseUrl=https://deploy-preview-${{GITHUB_PR_NUMBER}}--uuusoftware.netlify"
      #   env:
      #     CONFIG_VAR: 'pageLoadTimeout=150000,baseUrl=https://deploy-preview-${{GITHUB_PR_NUMBER}}--uuusoftware.netlify.app'
      # - run: echo "Your CONFIG__VAR is $CONFIG_VAR"
