name: End-to-end tests
on: issue_comment
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Check comments
        run: echo "Your PR_COMMENT is $PR_COMMENT"

        # run: echo "GITHUB_PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
        # run: echo "GITHUB_PR_NUMBER=$(echo $GITHUB_REF | awk -F / '{print $3}')" >> $GITHUB_ENV
      # - run: echo "pageLoadTimeout=150000,baseUrl=https://deploy-preview-${{ github.event.pull_request.number }}--uuusoftware.netlify"
      #   env:
      #     CONFIG_VAR: 'pageLoadTimeout=150000,baseUrl=https://deploy-preview-${{GITHUB_PR_NUMBER}}--uuusoftware.netlify.app'
      # - run: echo "Your CONFIG__VAR is $CONFIG_VAR"
